version: '3'
services:

  web:
    image: nginx:latest  # Use the latest Nginx image from Docker Hub
    ports:
      - "${PORT}:80"  # Map host port 80 to container port 80
    volumes:
      - ./src:/usr/share/nginx/html  # Mount the source directory to Nginx's default document root directory
      - ./config/nginx.conf:/etc/nginx/nginx.conf  # Mount a custom Nginx configuration file if needed